name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Set up Rust
      run: |
        rustup target add wasm32-wasi

    - name: Build
      run: cargo build --target wasm32-wasi --verbose
